title: Taimoor Alam
description: Technical Leader • Software Architect • Mentor • Lead Engineer • Typescript • Javascript • Nodejs • AWS • Python
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
